# yaml-language-server: $schema=https://app.stainlessapi.com/config.schema.json

organization:
  name: meorphis-test-4
  docs: https://docs.meorphis-test-4.com
  contact: support@acme.com
  github_org: meorphis-test-4
resources:
  accounts:
    methods:
      retrieve: get /accounts/{account_token}
      update: patch /accounts/{account_token}
    subresources:
      credit_configuration:
        methods:
          retrieve: get /accounts/{account_token}/credit_configuration
          update: patch /accounts/{account_token}/credit_configuration
        models:
          businessaccount: BusinessAccount
    models:
      accountconfiguration: AccountConfiguration
  cards:
    methods:
      create: post /cards
      retrieve: get /cards/{card_token}
      update: patch /cards/{card_token}
      provision: post /cards/{card_token}/provision
    subresources:
      financial_transactions:
        methods:
          retrieve: >-
            get
            /cards/{card_token}/financial_transactions/{financial_transaction_token}
    models:
      card: Card
      financialtransaction: FinancialTransaction
  status:
    methods:
      retrieve: get /status
package:
  node:
    name: meorphis-test-4
    repo: ''
  python:
    name: meorphis-test-4
    repo: ''
  java:
    name: meorphis-test-4
    repo: ''
    reverse_domain: "org.example"
  kotlin:
    name: meorphis-test-4
    repo: ''
  go:
    name: meorphis-test-4
    repo: ''
  ruby:
    name: meorphis-test-4
    repo: ''
settings:
  license: Apache-2.0
client_settings:
  opts:
    api_key:
      type: string
      auth:
        security_scheme: ApiKeyAuth
      read_env: MEORPHIS_TEST_4_API_KEY
environments:
  production: https://api.acme.com/v1
  environment_1: https://sandbox.acme.com/v1
query_settings:
  nested_format: brackets
  array_format: comma
readme:
  example_requests:
    default:
      type: request
      endpoint: get /status
      params: &ref_0 {}
    headline:
      type: request
      endpoint: get /status
      params: *ref_0
openapi:
  code_samples: mintlify