name: Upload OpenAPI spec to Stainless

on:
  push:
    branches: [main]

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'config/acme-openapi.yml'
          config_path: 'config/acme.stainless.yml'
          output_path: 'config/acme-openapi.documented.json'
      - uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'config/acme-openapi.documented.json'
          destination-username: 'emorphis'
          destination-repository: 'meorphis/docs'
          destination-directory: 'config'
          commit-email: 'meorphis@gmail.com'
